server {
    listen 80 default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /healthz {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }

    location = /front_asset_map.json {
        alias /shared/front_asset_map.json;
    }

    location /assets/js/ {
        try_files $uri @shared_js;
    }

    location @shared_js {
        root /shared;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
